// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_room_ from "./routes/[room].tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_connect from "./routes/api/connect.ts";
import * as $api_create_room from "./routes/api/create_room.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_send from "./routes/api/send.ts";
import * as $index from "./routes/index.tsx";
import * as $new from "./routes/new.tsx";
import * as $AddRoom from "./islands/AddRoom.tsx";
import * as $Chat from "./islands/Chat.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[room].tsx": $_room_,
    "./routes/_app.tsx": $_app,
    "./routes/api/connect.ts": $api_connect,
    "./routes/api/create_room.ts": $api_create_room,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/send.ts": $api_send,
    "./routes/index.tsx": $index,
    "./routes/new.tsx": $new,
  },
  islands: {
    "./islands/AddRoom.tsx": $AddRoom,
    "./islands/Chat.tsx": $Chat,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
